# comando exec para docker composer: docker-compose up

version: "3.8"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes: 
      - pgdata:/data/postgres
    network_mode: host
  # nome do serviço
  app:
    # informação q passo para dentro do app / o "." significa repositorio local
    build: .
    container_name: rentx
    # portas disponiveis na aplicação
    ports: 
      - 3333:3333
    # seria o workdir do dockerfile
    volumes:
      - .:/usr/app
    network_mode: host

volumes: 
  pgdata: 
    driver: local